dist: xenial
sudo: false
language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install --upgrade requests
  - pip install --upgrade websockets
  - pip install --upgrade pyyaml
script:
  - pip freeze
  - python setup.py test
